services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: client
        MYSQL_USER: root
        MYSQL_PASSWORD: root
